controller_list:
  - name: left_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
  
