

TwistCommand[] send_twist_command

JointSpeeds[] send_joint_speeds

ConstrainedPose[] reach_pose

ConstrainedJointAngles[] reach_joint_angles
uint32[] toggle_admittance_mode

SwitchControlMapping[] switch_control_mapping
uint32[] navigate_joints
uint32[] navigate_mappings

ChangeTwist[] change_twist

ChangeJointSpeeds[] change_joint_speeds

EmergencyStop[] apply_emergency_stop

Faults[] clear_faults

Delay[] delay

ActionHandle[] execute_action

GripperCommand[] send_gripper_command

Stop[] stop_action