initial_joint_positions: "-J joint_1 1.57
                        -J joint_2 -0.35
                        -J joint_3 3.14
                        -J joint_4 -2.00
                        -J joint_5 0
                        -J joint_6 -1.00
                        -J joint_7 1.57"