joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

  - name: "robotiq_2f_85_gripper_controller"
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - gripper_finger1_joint