# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.99
    has_acceleration_limits: true
    max_acceleration: 0.35
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.99
    has_acceleration_limits: true
    max_acceleration: 0.17
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.99
    has_acceleration_limits: true
    max_acceleration: 0.14
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.99
    has_acceleration_limits: true
    max_acceleration: 0.35
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.99
    has_acceleration_limits: true
    max_acceleration: 3.5
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.55
    has_acceleration_limits: true
    max_acceleration: 3.5
  right_finger_bottom_joint:
    has_velocity_limits: true
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 0