joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "gen3_lite_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  - name: "gen3_lite_2f_gripper_controller"
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - right_finger_bottom_joint