<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="worker_simple">
        <link name="worker_body_link">
            <inertial>
                <origin xyz="0 0 ${worker_height/2}" rpy="0 0 0" />
                <mass value="${worker_mass}" />
                <xacro:box_inertia mass="${worker_mass}" x="${worker_length}" y="${worker_width}" z="${worker_height}" />
            </inertial>
            <visual>
                <origin xyz="0 0 ${worker_height/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${worker_length} ${worker_width} ${worker_height}"/>
                </geometry>
                <material name="grey">
                    <color rgba="0.75 0.75 0.75 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${worker_height/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${worker_length} ${worker_width} ${worker_height}"/>
                </geometry>
            </collision>
        </link>

        <link name="mast_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${worker_mass}" />
                <xacro:cylinder_inertia mass="${mast_mass}" r="${mast_radius}" l="${mast_length} " />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${mast_radius}" length="${mast_length}" />
                </geometry>
                <material name="grey">
                    <color rgba="0.75 0.75 0.75 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${mast_radius}" length="${mast_length}" />
                </geometry>
            </collision>
        </link>

        <link name="spool_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${spool_mass}" />
                <xacro:cylinder_inertia mass="${spool_mass}" r="${spool_radius}" l="${spool_length} " />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${spool_radius}" length="${spool_length}" />
                </geometry>
                <material name="grey">
                    <color rgba="0.75 0.75 0.75 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${spool_radius}" length="${spool_length}" />
                </geometry>
            </collision>
        </link>

        <link name="bio_container_link">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${bio_container_mass}" />
                <xacro:box_inertia mass="${bio_container_mass}" x="${bio_container_length}" y="${bio_container_width}" z="${bio_container_height}" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://kortex_scripts/robot_equipment/meshes/linear_bio_holder.STL"/>
                </geometry>
                <material name="grey">
                    <color rgba="0.75 0.75 0.75 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://kortex_scripts/robot_equipment/meshes/linear_bio_holder.STL"/>
                </geometry>
            </collision>
        </link>

        <joint name="bio_container_worker_body_joint" type="fixed">
            <origin xyz="0 0.05 0.5" rpy="1.57 0 0" />
            <parent link="worker_body_link" />
            <child link="bio_container_link" />
            <axis xyz="0 0 0" />
        </joint>

        <joint name="spool_mast_joint" type="fixed">
            <origin xyz="0 0 ${-mast_length/2 - mast_height_offset + spool_length/2}" rpy="0 0 0" />
            <parent link="mast_link" />
            <child link="spool_link" />
            <axis xyz="0 0 0" />
        </joint>

        <joint name="worker_body_mast_joint" type="fixed">
            <origin xyz="${-worker_length/2 + mast_edge_center_distance} 0 ${mast_length/2 + worker_height + mast_height_offset}" rpy="0 0 0" />
            <parent link="worker_body_link" />
            <child link="mast_link" />
            <axis xyz="0 0 0" />
        </joint>

        <joint name="mast_chair_joint" type="fixed">
            <origin xyz="0 0 0.300" rpy="0 0 0" />
            <parent link="mast_link" />
            <child link="chair_link" />
            <axis xyz="0 0 0" />
        </joint>

    </xacro:macro>
</robot>